sudo: required
services:
  - docker

before_install:
  - docker build -t therealjaygray/complex-app -f ./client/Dockerfile.dev ./client
# add other test scripts to run here

script:
  - docker run -e CI=true therealjaygray/complex-app npm run yolo
## add more build scripts here

after_success:
  - docker build -t therealjaygray/multi-client ./client
  - docker build -t therealjaygray/multi-nginx ./nginx
  - docker build -t therealjaygray/multi-server ./server
  - docker build -t therealjaygray/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push therealjaygray/multi-client
  - docker push therealjaygray/multi-nginx
  - docker push therealjaygray/multi-server
  - docker push therealjaygray/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-703936373391
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
